spring.application.name=course-registration-backend

# server
server.port=${PORT:8081}

# database
spring.datasource.url=mysql://root:LlDYRNzFSJfEbWRTciYdypXYPdIXOkHE@switchback.proxy.rlwy.net:43078/railway
spring.datasource.username=root
spring.datasource.password=harishyam

# jpa / hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
